Update push repo

diff --git a/hooks/variants b/hooks/variants
--- a/hooks/variants
+++ b/hooks/variants
@@ -89,7 +89,7 @@ function push_variants() {
             docker tag "$(variant_image_name ${VARIANT_NAME})" "$(variant_image_name_stable ${VARIANT_NAME})"
             docker_push "$(variant_image_name_stable ${VARIANT_NAME})"
         fi
-        docker tag "$(variant_image_name ${VARIANT_NAME})" "$(variant_image_name_legacy ${VARIANT_NAME})"
-        docker_push "$(variant_image_name_legacy ${VARIANT_NAME})" || echo "Failed to push legacy image, ignoring"
+        # docker tag "$(variant_image_name ${VARIANT_NAME})" "$(variant_image_name_legacy ${VARIANT_NAME})"
+        # docker_push "$(variant_image_name_legacy ${VARIANT_NAME})" || echo "Failed to push legacy image, ignoring"
     done
 }
